spring.application.name=CustomerService
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://customer-db:3306/customerdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=root
# ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
booking-service.base-url=${BOOKING_SERVICE_URL:http://localhost:8081}
# sl4j för loggar får man får
#logging.level.root = info
#logging.level.root = warn
#logging.level.root = error
management.endpoints.web.exposure.include=health, info, metrics
# av någon anledning startar inte programmet lokalt, men i railway fungerar den,
# tror det har med jdbc länken att göra. tror det måste stå localhost där om den ska fungera att köra
#yahya lägger upp den grafana springboot på lektions materialet.
server.port=${PORT:8080}